### ISSUE TITLE
Update do bloków kół naukowych

### ISSUE THREAD

**Issue by CrunchyBaguette** [CrunchyBaguette/researchGroups#20]
![obraz](https://user-images.githubusercontent.com/68618094/203312973-5d5f5f5a-58c1-45d1-bef4-a6f63fc4e223.png)

- [ ] Zmienić kategorię na angielski
- [ ] Dodać zawijanie tekstu

**Comment by Kamil-Lontkowski** [comment]
To można zamknąć?
